/* Generated By:JavaCC: Do not edit this line. SqlGrammarTreeConstants.java Version 5.0 */
package com.tbc.paas.mql.grammar;

public interface SqlGrammarTreeConstants
{
  public int JJTVOID = 0;
  public int JJTDELETE = 1;
  public int JJTUPDATE = 2;
  public int JJTWHERE = 3;
  public int JJTUPDATECOLUMNS = 4;
  public int JJTUPDATECOLUMN = 5;
  public int JJTARITHMETICOPERATOR = 6;
  public int JJTINSERT = 7;
  public int JJTCOLUMNS = 8;
  public int JJTVALUES = 9;
  public int JJTSELECT = 10;
  public int JJTLIMITSEGMENT = 11;
  public int JJTLIMIT = 12;
  public int JJTOFFSET = 13;
  public int JJTCOLUMNSEGMENT = 14;
  public int JJTDISTINCT = 15;
  public int JJTFROMSEGMENT = 16;
  public int JJTWHERESEGMENT = 17;
  public int JJTCOLUMN = 18;
  public int JJTJOIN = 19;
  public int JJTJOINCONDITION = 20;
  public int JJTTABLE = 21;
  public int JJTNULL = 22;
  public int JJTNOT = 23;
  public int JJTIN = 24;
  public int JJTBINARYOPERATOR = 25;
  public int JJTGROUPSEGMENT = 26;
  public int JJTHAVING = 27;
  public int JJTBLOCKCONDITION = 28;
  public int JJTADD = 29;
  public int JJTOR = 30;
  public int JJTCONDITIONSLICE = 31;
  public int JJTLIKE = 32;
  public int JJTBETWEEN = 33;
  public int JJTORDERSEGMENT = 34;
  public int JJTORDER = 35;
  public int JJTAGGREGATE = 36;
  public int JJTCOLUMNNAME = 37;
  public int JJTFUNCTIONDISTINCT = 38;
  public int JJTALIAS = 39;
  public int JJTPARAMETER = 40;
  public int JJTPLACEHOLDER = 41;
  public int JJTVALUE = 42;
  public int JJTNUMBER = 43;
  public int JJTBOOLEAN = 44;


  public String[] jjtNodeName = {
    "void",
    "Delete",
    "Update",
    "Where",
    "UpdateColumns",
    "UpdateColumn",
    "ArithmeticOperator",
    "Insert",
    "Columns",
    "Values",
    "Select",
    "LimitSegment",
    "LIMIT",
    "OFFSET",
    "ColumnSegment",
    "Distinct",
    "FromSegment",
    "WhereSegment",
    "Column",
    "Join",
    "JoinCondition",
    "Table",
    "Null",
    "Not",
    "In",
    "BinaryOperator",
    "GroupSegment",
    "Having",
    "BlockCondition",
    "Add",
    "Or",
    "ConditionSlice",
    "Like",
    "Between",
    "OrderSegment",
    "Order",
    "Aggregate",
    "ColumnName",
    "FunctionDistinct",
    "Alias",
    "Parameter",
    "Placeholder",
    "Value",
    "Number",
    "Boolean",
  };
}
/* JavaCC - OriginalChecksum=d63950d8c1ea5d01b6ceea0d61076f25 (do not edit this line) */
